/**
 * Created by strawmanbobi
 * 2017-03-27
 */

var LS_KEY_ID = 'user_name';
var LS_KEY_TOKEN = 'token';

var CATEGORY_AC = 1;
var CATEGORY_TV = 2;
var CATEGORY_STB = 3;
var CATEGORY_NW = 4;
var CATEGORY_IPTV = 5;
var CATEGORY_DVD = 6;
var CATEGORY_FAN = 7;
var CATEGORY_PROJECTOR = 8;
var CATEGORY_STEREO = 9;
var CATEGORY_LIGHT_BULB = 10;
var CATEGORY_BSTB = 11;
var CATEGORY_CLEANING_ROBOT = 12;
var CATEGORY_AIR_CLEANER = 13;

var TRANSFER_STATE_NONE = 0;
var TRANSFER_STATE_BIN_FETCHED = 1;
var TRANSFER_STATE_BIN_ON_GOING = 2;
var TRANSFER_STATE_BIN_DONE = 3;